### PR TITLE
Move to Timeouts

### PR DESCRIPTION
**Pull request by TheUntraceable**
**Please describe the changes this PR makes and why it should be merged:**

This pr aims to move all `mutes` to the new Timeout feature DiscordJS v13.4 has. I haven't tested this but it *should* work. I wish I could edit the docs but I'm not the best with HTML and will leave that for someone to take a look at. I scrapped the unMute function as Discord now handles that.

**Status and versioning classification:**

- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Comment by Scraayp** [comment]
I will review this code after my break.

**Comment by TheUntraceable** [comment]
Sounds good, I also went ahead and added support for multiple guilds, I hope you have a good break 👍.

**Comment by Scraayp** [comment]
You forgot to update readme to add the multiple guild. 

Also, I don't think it's smart to add multiple guild option

**Review by Scraayp — APPROVED** [review]
Looks good to me. Just update the readme for guild options.

**Comment by Scraayp** [comment]
Also the docs are automatic. Just run:

``npm install``

``npm run generate-docs``

**Comment by TheUntraceable** [comment]
I updated the docs and the README, thanks for letting me know about JSDocs, I'll probably implement it into my own projects.

**Comment by Scraayp** [comment]
Okay,

Could you test everything out on a test bot. To make sure everything works, after I get the confirmation of you. I will push the pr.

**Pull request merged**
