### PR TITLE
`Ip filtering`

### PR DESCRIPTION
**Pull request by AADI0009**
Added Ip filtering

### CODE REVIEW

**Comment by Scraayp** [comment]
I'll into this after my vacation!

**Comment by Scraayp** [comment]
Has this been tested?

**Comment by Scraayp** [comment]
Has this been tested? @AADI0009

**Comment by AADI0009** [comment]
yes

**Review by Scraayp — CHANGES_REQUESTED** [review]
You need to add the property on top of the file with the IP warn enabled.

For example with the warnEnabled.
```js
 * @property {boolean} [warnEnabled=true] Whether warn sanction is enabled.
```

**Comment by AADI0009** [comment]
Will have to add properties for embeds too? @Scraayp

**Comment by Scraayp** [comment]
Embeds do have properties already, don't they?

**Review by Scraayp — APPROVED** [review]

**Pull request merged**
