### PR TITLE
Fix default values for booleans in options constructor

### PR DESCRIPTION
**Pull request by PeterTheHe**
**Please describe the changes this PR makes and why it should be merged:**
Fixes issue #125. Basically the same as before but it actually works.

### CODE REVIEW

**Comment by Scraayp** [comment]
I will check it asap. Busy with school and work last, so could take time!

**Review by Scraayp — APPROVED** [review]
Looks fine!

**Comment by Scraayp** [comment]
You have tested the code already?

**Comment by PeterTheHe** [comment]
Informally, yes (no unit tests though since I can't seem to find any)

**Comment by Scraayp** [comment]
Test the code in action first.

**Comment by PeterTheHe** [comment]
Done!

**Pull request merged**
