### PR TITLE
UpdateOptions Function

### PR DESCRIPTION
**Pull request by Scraayp**
**Please describe the changes this PR makes and why it should be merged:**
This will add a function which you can use to update the options while the service is running.

**Status and versioning classification:**

- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Comment by comicallybad** [comment]
Can you explain this further to me on discord?

**Comment by Scraayp** [comment]
@comicallybad What do you want to know exactly?

**Comment by comicallybad** [comment]
Sorry I got the email and you and someone working on a branch for my discord bot had similar names and so I thought it was a comment on a pull request for my bot from him lol my bad.

**Comment by Scraayp** [comment]
Oh. Haha! 👍

**Comment by Scraayp** [comment]
**Discontinued as of new update.**

*Will have a new pr after update.*

**Pull request closed without merging**
