### PR TITLE
Readme improvement

### PR DESCRIPTION
**Pull request by y21**
## Changes
- Replace `<` with `&lt;` and `>` with `&gt;` (HTML tags escaped, read [this](https://stackoverflow.com/questions/7381974/which-characters-need-to-be-escaped-in-html))
- Grammar fixes
- Sentences improved
- Typo fixes (`requieres` -> `requires`)

### CODE REVIEW

**Comment by Michael-J-Scofield** [comment]
I don't think the &lt; stuff is necessary in this instance but going to merge for the grammar fixes. Thanks.

**Comment by PlayerSchark** [comment]
This pull is still usable.
You have something in your code, that isn't in your README.md file. Eg. Kicks.
If you know that. Why you haven't fixed it? I'll never understand it...

**Comment by Michael-J-Scofield** [comment]
You're right you won't. Now get of Github

**Comment by Androz2091** [comment]
We have chosen to propose a simple example in the readme, which is why the kick option does not appear. It would be necessary to add a more complete documentation but it is good to keep this basic example.

**Comment by PlayerSchark** [comment]
I'll never use this package XD 
btw. are you to lazy to change it?

**Comment by Michael-J-Scofield** [comment]
Then don't use it. Nobody cares. We're not a premium support team available to you 24/7. Most people are busy

**Pull request merged**
