### PR TITLE
TypeScript rewrite

### PR DESCRIPTION
**Pull request by Androz2091**
Rewrite everything with TypeScript.

**Important breaking changes:** `exemptPermissions` was renamed to `ignoredPermissions`

* New examples folder
* Comments fixed in README

### CODE REVIEW

**Comment by Scraayp** [comment]
Good work bro!

**Comment by Androz2091** [comment]
So, it should be good.

I used `better-docs` to document the code, because `jsdoc` is not appropriate (specifying types in jsdoc + with typescript is redundant). But, sometimes, I had to add types, otherwise `better-docs` didn't render docs well (for example in `index.ts` line 468).

In addition, I couldn't find a good way to document default values without specifying types like line 468 for the `AntiSpamClientOptions` for example, and I think it's important. I don't know if using better-docs is the best solution.

**Comment by Scraayp** [comment]
For me it looks great

**Comment by Scraayp** [comment]
You can merge this to the development branch. 
I will take it over from there, will test it out for bugs ect...

**Comment by Androz2091** [comment]
@Scraayp You can use my branch to test the code. I don't want to merge this until we don't have a good solution for documentation.

**Comment by Scraayp** [comment]
Yeah i tested it. For me it did work without any changes. @Androz2091

**Comment by Androz2091** [comment]
All right. I will merge it as soon as possible.

**Review by adonyssantos — APPROVED** [review]

**Comment by adonyssantos** [comment]
Nice! But resolve conflicts.

**Pull request closed without merging**
