### PR TITLE
2.6.0

### PR DESCRIPTION
**Pull request by Scraayp**
__**Version 2.6.0:**__

**Adds:**
- Userleave | When user leaves the package removes him from the cache!
- Timemute | Mute someone for defined time in minutes
- Modlogs Mode | Send the modlogs in 'embed' modus or 'message' modus

**Removes:**
- Clearbotmessages which causes many bugs.
- V11 and V12 discord.js support

**Fixes:**
- Docs to only v13 support
- Delete message error
- Event names
- Docs

### CODE REVIEW

**Comment by Kief5555** [comment]
and add intents to docs

**Comment by Scraayp** [comment]
Done, thank you for the suggestions/feedback @Kief5555

**Comment by Kief5555** [comment]
> Done, thank you for the suggestions/feedback @Kief5555

Thanks

**Comment by Scraayp** [comment]
> > Done, thank you for the suggestions/feedback @Kief5555
> 
> Your welcome*

It's you're welcome :)

**Comment by Scraayp** [comment]
__**Version 2.6.0:**__

**Adds:**
- Userleave | When user leaves the package removes him from the cache!

**Removes:**
- Clearbotmessages which causes many bugs.
- V11 and V12 discord.js support

**Fixes:**
- Docs to only v13 support

**Comment by Kief5555** [comment]
When Is the next update?

**Comment by Kief5555** [comment]
Do you have an est of npm uploading?

**Comment by Kief5555** [comment]
For your info, 

```const client = new Client({
    intents: 32767,
});``` defines all intents. 

Some bots may require the "gateway intents" using the djs dev portal under "bot".
<img width="1062" alt="Screen Shot 2021-10-15 at 5 08 57 PM" src="https://user-images.githubusercontent.com/67562560/137565978-a450c443-5df1-4681-a413-5d528f472336.png">

**Comment by Scraayp** [comment]
Dm owner when admin spams

**Comment by Scraayp** [comment]
I'm sorry I had this todo lately. I will try to do it today!

**Comment by Scraayp** [comment]
The update has been delayed as the current workout doesn't work!

**Comment by Kief5555** [comment]
......

**Comment by Scraayp** [comment]
Ye I can't do shit it's not working! I mean I can't push a broken branch, because then rip bots!

**Comment by Kief5555** [comment]
how do u manual install 2.6?

**Comment by Scraayp** [comment]
Can't until I push it into npm. Or you could download it trough git npm I believe

**Comment by Kief5555** [comment]
I am on Mac too

Thanks, Kiefer

**Comment by Scraayp** [comment]
https://stackoverflow.com/questions/39732397/install-specific-branch-from-github-using-npm

**Comment by Scraayp** [comment]
Pretty good start of all fixes and new time mute option! Now warn and mute works. Time mute doesn't work yet as it doesn't remove the role after timeout!

**Comment by Kief5555** [comment]
when will you push to npm

**Comment by Scraayp** [comment]
> when will you push to npm

I expect this week. But it will depend if someone will actively review my code as backup for if something goes wrong!

**Comment by Scraayp** [comment]
Also I normally don't work on weekends. So this is all I did for you guys :)

**Comment by Scraayp** [comment]
Now only I want to make embed logs and then I will push it to npm

**Comment by Scraayp** [comment]
https://discord.gg/nK6hsyhe?event=909785083056115763

NOV 16 2pm (CEST)

**Comment by Scraayp** [comment]
The update has been delayed to. 15:00 (cest).

**Pull request merged**
