### PR TITLE
docs: fix small typo

### PR DESCRIPTION
**Pull request by oadpoaw**
**Please describe the changes this PR makes and why it should be merged:**
Fixes a typo in README.md. It should me `message` not `messageCreate`

**Status and versioning classification:**
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Scraayp** [comment]
As of v13 the client event has been named: "messageCreate".

https://discord.js.org/#/docs/discord.js/stable/class/Client?scrollTo=e-messageCreate

So no, it should be MessageCreate

**Comment by oadpoaw** [comment]
> As of v13 the client event has been named: "messageCreate".
> 
> https://discord.js.org/#/docs/discord.js/stable/class/Client?scrollTo=e-messageCreate
> 
> So no, it should be MessageCreate

Yep, but the variable name...

**Comment by oadpoaw** [comment]
@Scraayp

**Comment by Scraayp** [comment]
Oh wait now I see.

**Pull request closed without merging**
