### PR TITLE
Update

### PR DESCRIPTION
**Pull request by MrAugu**
Changelog:

- Exempt Users is now function.
- Exempt Roles is now a function.
- Exempt Guilds is now a function.
- Module is now a constructor.
- Implemented events upon emitting a warn, a ban, a successful warn, a successful ban and on data reset.
- New methods.
- Costructor options renamed to make more sense.
- Tags in warning messages as well in ban messages for even more customization.
- Fixed bug & glitches.
- More accuracy in detecting duplicate text and spam.

That is it for 2.0 update.

### CODE REVIEW

**Comment by Michael-J-Scofield** [comment]
I don't agree on making the excempts a function. This will probably over complicate the functionality for a lot of people. Can we remove this or make it optional?

**Comment by MrAugu** [comment]
All the settings are and will be optional all the time. For more simplicity `ignoredUsers` and `ignoredGuilds` we're added to simplify the setup of ignored users and guilds.

**Comment by Androz2091** [comment]
Perhaps what might be good is to remove the excempt() functions from the first codeblock so that novice users are not lost? Experienced people will go down lower and find this feature, no need to worry about it.

**Comment by Androz2091** [comment]
@Michael-J-Scofield what do you think?

**Pull request merged**
